version: '{branch}.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: Oetools.AblParser.sln
  verbosity: normal
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false